# Generated by Django 3.2.7 on 2021-10-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_contact_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='pincode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
